
name: Java Quality + Telegram

on:
  pull_request:
    branches: [ "dev" ]
    types: [ closed ]

jobs:
  quality:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'feature/ticket-') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Checkstyle
        run: |
          mvn clean verify | tee report.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: quality-report
          path: report.txt
      - name: Generate report
        if: always()
        run: |
          mkdir peresdReport
          echo "Pipeline Report" > peresdReport/peresdReport.txt
          echo "Repository: $git_rep" >> peresdReport/peresdReport.txt
          echo "Branch: $git_ref_n" >> peresdReport/peresdReport.txt
          echo "Commit: $git_sha" >> peresdReport/peresdReport.txt
          echo "Status: ${{ job.status }}" >> peresdReport/peresdReport.txt
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: peresdPip-report
          path: peresdReport/peresdReport.txt

  telegram:
    needs: quality
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.ID_GROUP }}
        run: |
         Date = $(date '+%Y-%m-%d')
          URL = "https://github.com/${git_rep}/actions/runs/${git_run}"

          txt = "Pipeline end

            репозиторий: $git_rep
            ветка: $git_ref_n
            дата: $Date
            статус работы: ${{ job.status }}

            Запуск:
            $URL"
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage \
          -d chat_id=${TELEGRAM_CHAT_ID} \
          -d text=$txt



